// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { Anton } from "next/font/google";
import "./globals.css";
// import Link from "next/link";
// import { SunIcon, MoonIcon } from "@heroicons/react/24/outline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Dark mode state (for client-side toggle)
  // This is a placeholder; real implementation would use useEffect and localStorage
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black text-black dark:text-white transition-colors duration-300`}>
        {/* <nav className="flex items-center justify-between px-8 py-4 border-b border-gray-200 dark:border-gray-800 bg-white/80 dark:bg-black/80 backdrop-blur z-50 sticky top-0">
          <div className="flex items-center gap-3">
            <span className="text-2xl font-bold text-red-600 tracking-tight">TEDx</span>
            <span className="text-lg font-semibold tracking-wide">Assam University</span>
          </div>
          <div className="flex gap-6 items-center">
            <Link href="/" className="hover:text-red-600 transition">Home</Link>
            <Link href="/about" className="hover:text-red-600 transition">About</Link>
            <Link href="/speakers" className="hover:text-red-600 transition">Speakers</Link>
            <Link href="/schedule" className="hover:text-red-600 transition">Schedule</Link>
            <Link href="/team" className="hover:text-red-600 transition">Team</Link>
            <Link href="/contact" className="hover:text-red-600 transition">Contact</Link>
            <button aria-label="Toggle dark mode" onClick={() => setDark(!dark)} className="ml-4 p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition">
              {dark ? <SunIcon className="w-5 h-5" /> : <MoonIcon className="w-5 h-5" />}
            </button>
          </div>
        </nav> */}
        <main className="min-h-[calc(100vh-64px)] font-[Anton]">{children}</main>
      </body>
    </html>
  );
}
